onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -expand -group gbt_x /tb_gbt_zynq_usplus/DUT/gbt_x/sfp1_gbitin_p
add wave -noupdate -expand -group gbt_x /tb_gbt_zynq_usplus/DUT/gbt_x/sfp1_gbitin_n
add wave -noupdate -expand -group gbt_x /tb_gbt_zynq_usplus/DUT/gbt_x/sfp1_los
add wave -noupdate -expand -group gbt_x /tb_gbt_zynq_usplus/DUT/gbt_x/sfp1_gbitout_p
add wave -noupdate -expand -group gbt_x /tb_gbt_zynq_usplus/DUT/gbt_x/sfp1_gbitout_n
add wave -noupdate -expand -group gbt_x /tb_gbt_zynq_usplus/DUT/gbt_x/sfp1_rateselect
add wave -noupdate -expand -group gbt_x /tb_gbt_zynq_usplus/DUT/gbt_x/sfp1_txdisable
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_TXRESET_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_RXRESET_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_TXRESET_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_RXRESET_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_CLK_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_TXFRAMECLK_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_TXCLKEn_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_RXFRAMECLK_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_RXCLKEn_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_TXWORDCLK_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_RXWORDCLK_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/TX_ENCODING_SEL_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_ISDATAFLAG_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/TX_PHCOMPUTED_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/TX_PHALIGNED_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/RX_ENCODING_SEL_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_RXREADY_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_ISDATAFLAG_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_ERRORDETECTED_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_ERRORFLAG_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_DEVSPECIFIC_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_RSTONBITSLIPEn_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_RSTONEVEN_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_TXREADY_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_RXREADY_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_DEVSPECIFIC_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_HEADERFLAG_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_HEADERLOCKED_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/MGT_RSTCNT_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_TXDATA_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/GBT_RXDATA_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/WB_TXDATA_i
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/WB_RXDATA_o
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_txencdata_s
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_txclkfromDesc_s
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_txwordclk_s
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_rxwordclk_s
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_txword_s
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_rxword_s
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_headerflag_s
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxencdata_s
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearboxready_s
add wave -noupdate -group gbt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxclkengearbox_s
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_RESET_I
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_FRAMECLK_I
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_CLKEN_i
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_ENCODING_SEL_i
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/READY_O
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_ISDATA_FLAG_ENABLE_I
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_ISDATA_FLAG_O
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_ERROR_DETECTED
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_BIT_MODIFIED_FLAG
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_FRAME_I
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_COMMON_FRAME_O
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_EXTRA_FRAME_WIDEBUS_O
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/rxFrame_from_deinterleaver
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/rxCommonFrame_from_reedSolomonDecoder
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/error_detected_lsb
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/error_detected_msb
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_COMMON_FRAME_gbt_s
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_EXTRA_FRAME_WIDEBUS_gbt_s
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_ERROR_DETECTED_gbt_s
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_BIT_MODIFIED_FLAG_gbt_s
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_COMMON_FRAME_wb_s
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_EXTRA_FRAME_WIDEBUS_wb_s
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_ERROR_DETECTED_wb_s
add wave -noupdate -group decoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/RX_BIT_MODIFIED_FLAG_wb_s
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/RX_RESET_I
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/RX_WORDCLK_I
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/MGT_CLK_I
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/RX_BITSLIPCMD_i
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/RX_BITSLIPCMD_o
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/RX_HEADERLOCKED_i
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/RX_BITSLIPISEVEN_i
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/RX_RSTONBITSLIP_o
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/RX_ENRST_i
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/RX_RSTONEVEN_i
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/DONE_o
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/READY_o
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/bitSlitRst
add wave -noupdate -group rxBitSlipControl /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/rxBitSlipControl/bitSlitRst_sync
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/RX_WORDCLK_I
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/RX_RESET_I
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/RX_BITSLIP_CMD_O
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/MGT_BITSLIPDONE_i
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/RX_WORD_I
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/RX_BITSLIPISEVEN_o
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/RX_HEADER_LOCKED_O
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/RX_HEADER_FLAG_O
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/state
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/psAddress
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/shiftPsAddr
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/bitSlipCmd
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/headerFlag_s
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/RX_HEADER_LOCKED_s
add wave -noupdate -group patternSearch /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtxLatOpt_gen(1)/patternSearch/RX_BITSLIPISEVEN_s
add wave -noupdate -group dpram_rx /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearbox_multilink_gen(1)/gbt_rxgearbox_inst/rxGearboxStd_gen/rxGearboxStd/dpram/WR_EN_I
add wave -noupdate -group dpram_rx /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearbox_multilink_gen(1)/gbt_rxgearbox_inst/rxGearboxStd_gen/rxGearboxStd/dpram/WR_CLK_I
add wave -noupdate -group dpram_rx /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearbox_multilink_gen(1)/gbt_rxgearbox_inst/rxGearboxStd_gen/rxGearboxStd/dpram/WR_ADDRESS_I
add wave -noupdate -group dpram_rx /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearbox_multilink_gen(1)/gbt_rxgearbox_inst/rxGearboxStd_gen/rxGearboxStd/dpram/WR_DATA_I
add wave -noupdate -group dpram_rx /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearbox_multilink_gen(1)/gbt_rxgearbox_inst/rxGearboxStd_gen/rxGearboxStd/dpram/RD_CLK_I
add wave -noupdate -group dpram_rx /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearbox_multilink_gen(1)/gbt_rxgearbox_inst/rxGearboxStd_gen/rxGearboxStd/dpram/RX_CLKEN_i
add wave -noupdate -group dpram_rx /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearbox_multilink_gen(1)/gbt_rxgearbox_inst/rxGearboxStd_gen/rxGearboxStd/dpram/RD_ADDRESS_I
add wave -noupdate -group dpram_rx /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearbox_multilink_gen(1)/gbt_rxgearbox_inst/rxGearboxStd_gen/rxGearboxStd/dpram/RD_DATA_O
add wave -noupdate -group dpram_rx /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxgearbox_multilink_gen(1)/gbt_rxgearbox_inst/rxGearboxStd_gen/rxGearboxStd/dpram/dOutB_from_dpram
add wave -noupdate -group gbt_data_x -expand /tb_gbt_zynq_usplus/gbt_data_x/ClkRs_ix
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/data_received
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/los
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/rate_select
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/tx_disable
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/data_sent
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/tx_frameclk
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/tx_wordclk
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/tx_clken
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/tx_valid
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/rx_frameclk
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/rx_wordclk
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/rx_clken
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/rx_valid
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/mgt_headerflag
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/tx_ready
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/rx_ready
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/link_ready
add wave -noupdate -group gbt_data_x /tb_gbt_zynq_usplus/gbt_data_x/bitslip_reset
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/ClkRs_ix
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/ClkRsRef_ix
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/data_received
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/data_sent
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/los
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/rate_select
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/tx_disable
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/rx_frameclk
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/tx_frameclk
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/tx_wordclk
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/rx_wordclk
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/tx_clken
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/rx_clken
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/tx_valid
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/rx_valid
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/mgt_headerflag
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/tx_ready
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/rx_ready
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/link_ready
add wave -noupdate -group gbt_data_vfc /tb_gbt_zynq_usplus/gbt_data_vfc/bitslip_reset
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/ClkRs_ix
add wave -noupdate -group serdes -expand /tb_gbt_zynq_usplus/i_serdes/ClkRxGBT_ix
add wave -noupdate -group serdes -expand /tb_gbt_zynq_usplus/i_serdes/ClkTxGBT_ix
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/data_ib32
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/resetflags_i
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/Rx_i
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/data_ob32
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/Tx_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/SerialLinkUp_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/RxLocked_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/TxBusy_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/newdata_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/TxEmptyFifo_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/txerror_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/rxlol_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/RxDataFifo_ob32
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/TxDataFifo_ib32
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/TxFullFifo_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/RxEmptyFifo_o
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/TxWrEnFifo_i
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/RxRdEnFifo_i
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/txerror
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/LinkWentUp
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/LinkWentDown
add wave -noupdate -group serdes /tb_gbt_zynq_usplus/i_serdes/SerialLinkUp
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/ClkRs_ix
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/ClkRxGBT_ix
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/ClkTxGBT_ix
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/data_ib32
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/resetflags_i
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/Rx_i
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/data_ob32
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/Tx_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/SerialLinkUp_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/RxLocked_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/TxBusy_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/newdata_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/TxEmptyFifo_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/txerror_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/rxlol_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/RxDataFifo_ob32
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/TxDataFifo_ib32
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/TxFullFifo_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/RxEmptyFifo_o
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/TxWrEnFifo_i
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/RxRdEnFifo_i
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/txerror
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/LinkWentUp
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/LinkWentDown
add wave -noupdate -group vfc_serdes /tb_gbt_zynq_usplus/i_vfc_serdes/SerialLinkUp
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/RX_FRAMECLK_I
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/RX_CLKEN_i
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/RX_COMMON_FRAME_ENCODED_I
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/RX_COMMON_FRAME_O
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/ERROR_DETECT_O
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/s1_from_syndromes
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/s2_from_syndromes
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/s3_from_syndromes
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/s4_from_syndromes
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/detIsZero_from_lambdaDeterminant
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/error1loc_from_errorLocPolynomial
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/error2loc_from_errorLocPolynomial
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/xx0_from_chienSearch
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/xx1_from_chienSearch
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/corCoeffs_from_rsTwoErrorsCorrect
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/bit_diff
add wave -noupdate -group reedSolomonDecoder /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/error_detected
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/POLY_COEFFS_I
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/S1_O
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/S2_O
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/S3_O
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/S4_O
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/net1
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/net2
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/net3
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/net4
add wave -noupdate -group syndroms /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/gbt_rxdatapath_multilink_gen(1)/gbt_rxdatapath_inst/decoder/gbtFrame_gen/reedSolomonDecoder60to119/syndromes/syndrome_from_syndromeEvaluator
add wave -noupdate -group serial_registers_test -expand /tb_gbt_zynq_usplus/gbt_rx_clkrs
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/data_arrived_vfc
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/vfc_linkup
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/data_from_mcoi
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/sc_idata_vfc
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/sc_odata_vfc
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/data_arrived
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/linkup
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/data_from_vfc
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/sc_idata
add wave -noupdate -group serial_registers_test /tb_gbt_zynq_usplus/sc_odata
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_REFCLK_i
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_RXUSRCLK_o
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_TXUSRCLK_o
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_TXRESET_i
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_RXRESET_i
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_TXREADY_o
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_RXREADY_o
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/RX_HEADERLOCKED_o
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/RX_HEADERFLAG_o
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_RSTCNT_o
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_AUTORSTEn_i
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_AUTORSTONEVEN_i
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_USRWORD_i
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_USRWORD_o
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_DEVSPEC_i
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_DEVSPEC_o
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rx_wordclk_sig
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/tx_wordclk_sig
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxoutclk_sig
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/txoutclk_sig
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rx_reset_done
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/tx_reset_done
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxResetDone_r3
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/txResetDone_r2
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxResetDone_r2
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/txResetDone_r
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxResetDone_r
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxfsm_reset_done
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/txfsm_reset_done
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/txuserclkRdy
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxuserclkRdy
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtwiz_buffbypass_tx_reset_in_s
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtwiz_buffbypass_rx_reset_in_s
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxpmaresetdone
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/txpmaresetdone
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/test1
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/test2
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/run_to_rxBitSlipControl
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxBitSlip_from_rxBitSlipControl
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxBitSlip_to_gtx
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/done_from_rxBitSlipControl
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rstBitSlip_FSM
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/mgtRst_from_bitslipCtrl
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rx_reset_sig
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/tx_reset_sig
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/resetGtxRx_from_rxBitSlipControl
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/resetGtxTx_from_rxBitSlipControl
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/txprgdivresetdone_int
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtwiz_userclk_tx_reset_int
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtwiz_userclk_rx_reset_int
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtwiz_userclk_tx_active_int
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/gtwiz_userclk_rx_active_int
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rxBuffBypassRst
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/resetAllMgt
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/MGT_USRWORD_s
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/bitSlipCmd_to_bitSlipCtrller
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/ready_from_bitSlipCtrller
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rx_headerlocked_s
add wave -noupdate -group mgt_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_inst/mgt_inst/rx_bitslipIsEven_s
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/gbt_clk_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/tx_frameclk_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/rx_frameclk_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/tx_clken_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/rx_clken_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/mgtclk_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/general_reset_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/tx_reset_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/rx_reset_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/mgt_tx_rstdone_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/mgt_rx_rstdone_i
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/qpll_locked
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/cpll_locked
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/mgt_tx_reset_o
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/mgt_rx_reset_o
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/gbt_tx_reset_o
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/gbt_rx_reset_o
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/genReset_s
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/mgtTxReset_s
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/mgtRxReset_s
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/gbtTxReset_s
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/gbtRxReset_s
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/genRstMgtClk_s
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/genRstMgtClk_sync_s
add wave -noupdate -group gefe_mode_reset /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rst_gen(1)/gefe_mode_reset/gbtbank_gefe_mode_reset/state
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/xcvrclk
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/xcvrclk1
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/frameclk_40mhz
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/rx_frameclk_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/rx_wordclk_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/tx_frameclk_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/tx_wordclk_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/tx_clken
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/rx_clken
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/rx_valid
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/mgt_headerflag
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_general_reset_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_reset_error_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_rx_p
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_rx_n
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_tx_p
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_tx_n
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_gbt_data_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_wb_data_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/tx_data_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/wb_data_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_gbt_data_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_wb_data_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_drp_clk
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_powergood_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_cplllock_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_qpll1lock_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_cdrlock_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_mgt_recclk_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/tx_encoding_sel_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_tx_isdata_sel_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/rx_encoding_sel_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_rxframeclk_alignpatter_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_rxbitslit_rstoneven_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_gbttx_ready_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_gbtrx_ready_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_link_ready_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_tx_aligned_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_tx_aligncomputed_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_rx_isdata_sel_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_rx_errordetected_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_rx_bitmodified_flag_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_rxbitslip_rst_cnt_o
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_loopback_i
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_tx_pol
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtbank_rx_pol
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_txreset_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_txdata_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/wb_txdata_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/mgt_txwordclk_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/mgt_rxwordclk_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/mgt_txreset_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/mgt_rxreset_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/mgt_txready_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/mgt_rxready_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/mgt_devspecific_to_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/mgt_devspecific_from_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/resetOnBitslip_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_rxreset_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_rxready_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbt_rxdata_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/wb_rxdata_s
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/gbtBank_rxEncodingSel
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/txData_from_gbtBank_pattGen
add wave -noupdate -group gbt_expanded_inst /tb_gbt_zynq_usplus/DUT/gbt_expanded_inst/txwBData_from_gbtBank_pattGen
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 2} {686057680 ps} 0} {{Cursor 2} {109517818 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 481
configure wave -valuecolwidth 245
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {109494791 ps} {109667179 ps}
